package app.common.enums;

/** PacketType. */
public enum PacketType {
  LOGIN,
  REGISTER,
  PLACE_BID,
  CREATE_AUCTION,
  CHAT,
  FETCH_AUCTION_SUMMARIES,
  FETCH_AUCTION_HISTORY,
  FETCH_AUCTION_DETAIL,
  UNWATCH_AUCTION,
  FETCH_AUCTION_RESULT,
  FETCH_SELLER_ITEMS,
  UPDATE_ITEM,
  DELETE_ITEM,
  FETCH_USER_LIST,
  CANCEL_AUCTION,
  DEPOSIT,
  CHAT_MESSAGE,
  AUCTION_CREATED,
  BID_PLACED,
  AUCTION_CANCELLED,
  AUCTION_SUMMARIES_UPDATED,
  AUCTION_DETAIL_UPDATED,
  WALLET_UPDATED,
  AUCTION_PAID_NOTICE,
  ERROR
}
