package app.common.enums;

/** RequestType. */
public enum RequestType {
  LOGIN,
  REGISTER,
  PLACE_BID,
  CREATE_AUCTION,
  UPDATE_AUCTION,
  CHAT,
  FETCH_AUCTION_SUMMARIES,
  FETCH_AUCTION_HISTORY,
  FETCH_AUCTION_DETAIL,
  UNWATCH_AUCTION,
  FETCH_AUCTION_RESULT,
  FETCH_SELLER_ITEMS,
  FETCH_USER_LIST,
  CANCEL_AUCTION,
  DEPOSIT,
  SETTLE_WALLET
}
