package app.common.enums;

/** ResponseType. */
public enum ResponseType {
  LOGIN_RESULT,
  REGISTER_RESULT,
  PLACE_BID_RESULT,
  SET_AUTO_BID_RESULT,
  DISABLE_AUTO_BID_RESULT,
  CREATE_AUCTION_RESULT,
  UPDATE_AUCTION_RESULT,
  CHAT_RESULT,
  AUCTION_SUMMARIES_RESULT,
  AUCTION_HISTORY_RESULT,
  AUCTION_RESULT,
  AUCTION_RESULT_FETCHED,
  SELLER_ITEMS_RESULT,
  USER_LIST_RESULT,
  CANCEL_AUCTION_RESULT,
  DEPOSIT_RESULT,
  SETTLE_WALLET_RESULT,

  USER_BANNED_NOTICE,

  CHAT_MESSAGE,
  AUCTION_CREATED,
  BID_PLACED,
  AUCTION_CANCELLED,
  AUCTION_SUMMARIES_UPDATED,
  AUCTION_DETAIL_UPDATED,
  WALLET_UPDATED,
  AUCTION_PAID_NOTICE,
  UPLOAD_IMAGE,
  FETCH_ITEM_IMAGE,
  UPLOAD_AVATAR,
  FETCH_AVATAR,
  ERROR
}
