package app.enums;

public enum RequestType {
  LOGIN,
  REGISTER,
  PLACE_BID,
  CREATE_AUCTION,
  GET_AUCTIONS,
  GET_AUCTION_DETAIL,
  SEND_MESSAGE,
  AUTO_BID,
  GET_CHAT_HISTORY,
  GET_NOTIFICATIONS,
  GET_BID_HISTORY
}
